import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Changed import
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto', // Same pattern, just renamed
  display: 'swap',
  weight: ['400', '500', '700'], // Added weights (required for Roboto)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}> {/* Identical structure */}
        {children}
      </body>
    </html>
  );
}